"use client";

import { useActionState } from "react";
import { ArrowRight, LoaderCircle } from "lucide-react";
import { createBookingAction, type BookingActionState } from "@/app/admin/actions/bookings";
import { site } from "@/content/site";
import type { Enquiry } from "@/lib/admin/data";

export function BookingForm({ enquiry, customerId }: { enquiry?: Enquiry | null; customerId?: string }) {
  const [state, action, pending] = useActionState(createBookingAction, {} as BookingActionState);
  return <form className="admin-form-card" action={action}><h2>{enquiry ? "Convert enquiry to booking" : "Record a booking"}</h2><p>{enquiry ? `${enquiry.customer?.full_name || "Customer"} · ${enquiry.customer?.phone}` : "Add an actual rental to keep revenue and customer segments accurate."}</p>{enquiry ? <input type="hidden" name="enquiryId" value={enquiry.id} /> : null}<input type="hidden" name="customerId" value={customerId || enquiry?.customer_id || ""} /><div className="admin-form-grid"><div className="admin-field admin-field-full"><label htmlFor="booking-car">Car</label><select id="booking-car" name="carSlug" defaultValue={enquiry?.car_slug || site.fleet[0].slug}>{site.fleet.map((car) => <option value={car.slug} key={car.slug}>{car.name}</option>)}</select></div><div className="admin-field"><label htmlFor="booking-start">Start date</label><input id="booking-start" type="date" name="startDate" defaultValue={enquiry?.pickup_date} required /></div><div className="admin-field"><label htmlFor="booking-end">End date</label><input id="booking-end" type="date" name="endDate" defaultValue={enquiry?.return_date} required /></div><div className="admin-field"><label htmlFor="booking-amount">Total amount (₹)</label><input id="booking-amount" type="number" name="amountTotal" min="0" step="0.01" placeholder="6500" required /></div><div className="admin-field"><label htmlFor="booking-deposit">Deposit (₹)</label><input id="booking-deposit" type="number" name="deposit" min="0" step="0.01" defaultValue="5000" required /></div><div className="admin-field admin-field-full"><label htmlFor="booking-status">Booking status</label><select id="booking-status" name="status" defaultValue="confirmed"><option value="confirmed">Confirmed</option><option value="ongoing">Ongoing</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><div className="admin-field admin-field-full"><label htmlFor="booking-notes">Notes</label><textarea id="booking-notes" name="notes" defaultValue={enquiry?.message || ""} placeholder="Payment notes, pickup details or special requests…" /></div></div>{state.message ? <p className="admin-form-error" role="alert">{state.message}</p> : null}<div className="admin-form-actions"><button className="admin-primary-button" disabled={pending} type="submit">{pending ? <><LoaderCircle size={15} className="animate-spin" /> Saving…</> : <>Create booking <ArrowRight size={15} /></>}</button></div></form>;
}
